'use client';

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';

export default function ReportsPage() {
  const reports = [
    {
      id: 1,
      name: 'Weekly Churn Intelligence',
      category: 'Retention',
      dateRange: 'Jan 15–21, 2024',
      generatedBy: 'Automated',
      lastAccessed: '2 hours ago',
      fileSize: '2.3 MB',
      downloads: 24,
    },
    {
      id: 2,
      name: 'Monthly Revenue Performance',
      category: 'Finance',
      dateRange: 'January 2024',
      generatedBy: 'Automated',
      lastAccessed: '1 day ago',
      fileSize: '4.1 MB',
      downloads: 61,
    },
    {
      id: 3,
      name: 'Acquisition Channel Analysis',
      category: 'Marketing',
      dateRange: 'Q4 2023',
      generatedBy: 'Sarah Admin',
      lastAccessed: '3 days ago',
      fileSize: '1.8 MB',
      downloads: 18,
    },
    {
      id: 4,
      name: 'Customer Segmentation Summary',
      category: 'Analytics',
      dateRange: 'January 2024',
      generatedBy: 'Automated',
      lastAccessed: '6 hours ago',
      fileSize: '3.2 MB',
      downloads: 42,
    },
  ];

  const scheduledReports = [
    {
      name: 'Weekly Churn Intelligence',
      schedule: 'Every Friday – 08:00',
      format: 'PDF',
      recipients: 'Retention Team',
      status: 'Active',
      nextRun: 'Jan 26, 2024',
    },
    {
      name: 'Monthly Revenue Performance',
      schedule: '1st of Every Month',
      format: 'CSV',
      recipients: 'Finance Department',
      status: 'Active',
      nextRun: 'Feb 1, 2024',
    },
    {
      name: 'Quarterly Executive Summary',
      schedule: 'Every 3 Months',
      format: 'PDF + CSV',
      recipients: 'Executive Team',
      status: 'Paused',
      nextRun: 'Mar 30, 2024',
    },
  ];

  return (
    <div className="min-h-screen bg-slate-50 p-8 space-y-8">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-semibold text-slate-900">
            Reports & Data Exports
          </h1>
          <p className="text-slate-600">
            Generate, schedule and distribute intelligence reports across teams
          </p>
        </div>

        <div className="flex gap-3">
          <Button variant="outline">Create Report</Button>
          <Button className="bg-indigo-600 hover:bg-indigo-700 text-white">
            Schedule Automation
          </Button>
        </div>
      </div>

      {/* KPI Strip */}
      <div className="grid grid-cols-2 md:grid-cols-4 xl:grid-cols-6 gap-4">
        {[
          { label: 'Total Reports', value: '42' },
          { label: 'Automated Reports', value: '18' },
          { label: 'Reports Generated (30d)', value: '128' },
          { label: 'Avg Delivery Time', value: '32 sec' },
          { label: 'Active Schedules', value: '9' },
          { label: 'Storage Used', value: '2.6 GB' },
        ].map((metric, idx) => (
          <Card key={idx}>
            <CardContent className="p-4">
              <p className="text-xs text-slate-500">{metric.label}</p>
              <p className="text-2xl font-semibold text-slate-900">
                {metric.value}
              </p>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Report Library */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {reports.map((report) => (
          <Card
            key={report.id}
            className="hover:shadow-md transition-shadow"
          >
            <CardContent className="p-5 space-y-3">
              <div className="flex items-start justify-between">
                <div>
                  <h3 className="text-lg font-semibold text-slate-900">
                    {report.name}
                  </h3>
                  <p className="text-sm text-slate-600">
                    {report.dateRange} • Generated by {report.generatedBy}
                  </p>
                </div>

                <Badge variant="secondary">{report.category}</Badge>
              </div>

              <div className="grid grid-cols-2 md:grid-cols-4 gap-3 text-xs text-slate-600">
                <div>📦 {report.fileSize}</div>
                <div>⬇️ {report.downloads} downloads</div>
                <div>🕒 {report.lastAccessed}</div>
                <div>📊 Accuracy Validated</div>
              </div>

              <div className="flex gap-2 pt-2 flex-wrap">
                <Button size="sm" variant="outline">
                  Preview
                </Button>
                <Button size="sm" variant="outline">
                  Download CSV
                </Button>
                <Button size="sm" variant="outline">
                  Download PDF
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  className="text-red-600 border-red-300 hover:bg-red-50"
                >
                  Delete
                </Button>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Scheduled Automation */}
      <Card>
        <CardHeader className="flex flex-row items-center justify-between">
          <CardTitle>Scheduled Report Automation</CardTitle>
          <Badge variant="secondary">Live Schedules</Badge>
        </CardHeader>

        <CardContent>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b text-slate-600">
                  <th className="py-3 text-left">Report</th>
                  <th className="py-3 text-left">Schedule</th>
                  <th className="py-3 text-left">Format</th>
                  <th className="py-3 text-left">Recipients</th>
                  <th className="py-3 text-left">Next Run</th>
                  <th className="py-3 text-left">Status</th>
                  <th className="py-3 text-left">Actions</th>
                </tr>
              </thead>

              <tbody>
                {scheduledReports.map((item, idx) => (
                  <tr key={idx} className="border-b hover:bg-slate-50">
                    <td className="py-3 font-medium">{item.name}</td>
                    <td className="py-3">{item.schedule}</td>
                    <td className="py-3">{item.format}</td>
                    <td className="py-3">{item.recipients}</td>
                    <td className="py-3">{item.nextRun}</td>
                    <td className="py-3">
                      <Badge
                        className={
                          item.status === 'Active'
                            ? 'bg-green-100 text-green-700'
                            : 'bg-yellow-100 text-yellow-700'
                        }
                      >
                        {item.status}
                      </Badge>
                    </td>
                    <td className="py-3 flex gap-2">
                      <Button size="sm" variant="outline">
                        Edit
                      </Button>
                      <Button size="sm" variant="outline">
                        Pause
                      </Button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
